apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyguard
  labels:
    app: keyguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyguard
  template:
    metadata:
      labels:
        app: keyguard
      annotations:
        deployedAt: "{{ date "20060102150405" .Release.Time }}"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          image: cromega/keyguard:latest
          imagePullPolicy: Always
          env:
            - name: KG_PUBLIC_URL
              value: "https://{{ .Values.publicHostname }}"
            - name: KG_PRIVATE_KEY
              value: "/etc/keyguard/private_key"
            - name: KG_YUBI_CLIENT_ID
              value: "{{ .Values.yubico.clientId }}"
            - name: KG_YUBI_API_KEY
              value: "{{ .Values.yubico.apiKey }}"
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 64Mi
          volumeMounts:
            - name: private-key
              mountPath: "/etc/keyguard"
              readOnly: true
      volumes:
        - name: private-key
          secret:
            secretName: keyguard-private-key
            defaultMode: 0444
