apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keyguard
  labels:
    app: keyguard
spec:
  rules:
  - host: {{ .Values.publicHostname }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: keyguard
              port:
                number: 80
  {{- if .Values.tlsSecret }}
  tls:
    - hosts: [{{ .Values.publicHostname }}]
      secretName: {{ .Values.tlsSecret }}
  {{- end }}
