apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keyguard
spec:
  rules:
  - host: {{ .Values.public_url }}
    http:
      paths:
      - backend:
          serviceName: keyguard
          servicePort: 80
