apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyguard
  labels:
    app: keyguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyguard
  template:
    metadata:
      labels:
        app: keyguard
    spec:
      containers:
        - name: app
          image: cromega/keyguard:latest
          imagePullPolicy: Always
          env:
            - name: KG_PUBLIC_URL
              value: $KG_PUBLIC_URL
            - name: KG_PRIVATE_KEY
              value: $KG_PRIVATE_KEY
            - name: KG_YUBI_CLIENT_ID
              value: $KG_YUBI_CLIENT_ID
            - name: KG_YUBI_API_KEY
              value: "/etc/keyguard/id_rsa"
          volumeMounts:
            - name: private-key
              mountPath: "/etc/keyguard"
              readOnly: true
      volumes:
        - name: private-key
          secret:
            secretName: private-key
            defaultMode: 0600
