resources:
- name: code
  type: git
  source:
    uri: git@github.com:cromega/keyguard
    private_key: {{deploy-key}}
- name: image
  type: docker-image
  source:
    repository: cromega/keyguard
    username: cromega
    password: {{dockerhub-password}}

jobs:
- name: build
  plan:
  - get: code
    trigger: true
  - task: test
    file: code/ci/test.yml
  - put: image
    params:
      build: code/
