name: DockerImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Test
      run: |
        docker build --target builder -t base .
        docker run --rm base go test -v

    - name: Build final image
      run: docker build -t cromega/keyguard .

    - name: Docker push
      env:
        DOCKERHUB_PW: ${{ secrets.dockerhub_password }}
      run: |
        echo "$DOCKERHUB_PW" | docker login -u cromega --password-stdin
        docker push cromega/keyguard

  trigger-deploy:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deployment
      env:
        TOKEN: ${{ secrets.repo_token }}
      run: |
        curl -X POST \
          -H "Authorization: token $TOKEN" \
          https://api.github.com/repos/cromega/sublimia-platform/dispatches \
          --data '{"event_type":"deploy:keyguard"}'
