name: DockerImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.15.2-alpine3.12
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Prepare container
      run: |
        apk add --no-cache openssh-keygen
        chmod 600 testdata/real_id_rsa

    - name: Test
      run: |
        export CGO_ENABLED=0
        go test -v

  push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKERHUB_PW: ${{ secrets.dockerhub_password }}
      run: echo "$DOCKERHUB_PW" | docker login -u cromega --password-stdin

    - name: Build
      run: docker build -t cromega/keyguard .
    - name: Push
      run: docker push cromega/keyguard

  trigger-deploy:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger deployment
      env:
        TOKEN: ${{ secrets.repo_token }}
      run: |
        curl -X POST \
          -H "Authorization: token $TOKEN" \
          https://api.github.com/repos/cromega/sublimia-platform/dispatches \
          --data '{"event_type":"deploy:keyguard"}'
